<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'О нас';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="buttons-group">
    <div class="go-home-button__wrapper">
        <a href="/" class="go-home-button__link">
            <div class="go-home-button">
                <i class="fas fa-home"></i> <?= Yii::t('site', 'На главную страницу') ?>
            </div>
        </a>
    </div>
</div>
<div class="site-about">
    <?php if (Yii::$app->language === 'ru'): ?>
    <h1>
        <?= Yii::t('site', 'ГКП НА ПХВ "Городская поликлиника № 8"') ?>
    </h1>

    <p class="text-center">
        <img src="/img/fon.jpg" alt="building" style="width: 100%;">
    </p>

        <header class="article-header clearfix" style='box-sizing: border-box; display: block; clear: both; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
            <h1 class="article-title" style='box-sizing: border-box; font-size: 21.6px; margin: 0px; line-height: 1.15538em; font-family: "Open Sans"; font-weight: 300 !important; color: inherit; text-rendering: optimizelegibility; padding-top: 0.3em; padding-bottom: 0.1em; text-transform: uppercase; text-align: center;'><a href="http://gp8shymkent.kz/about/sfera-deyatelnosti/18-demo-content/157-sfera-deyatelnosti" style='box-sizing: border-box; background: transparent; color: inherit; text-decoration: none; transition: all 0.2s ease-in 0s; font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>СФЕРА ДЕЯТЕЛЬНОСТИ</a></h1>
        </header>
        <section class="article-content clearfix" style='box-sizing: border-box; display: block; clear: none; margin-top: 0px; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
            <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif; text-align: justify;'>Государственное коммунальное предприятие на праве хозяйственного ведения &laquo;Городская поликлиника № 8&raquo; Управления здравоохранения ЮКО находится на страже здоровья более 38000 жителей Энбекшинского и Аль-Фарабийского районов г.Шымкента.<br style="box-sizing: border-box;"><br style="box-sizing: border-box;"></p>
            <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif; text-align: justify;'>Медицинские услуги оказывают 2 семейных отделения, врачи 18 специальностей, дневной стационар, кабинет планирования семьи, отделение профилактики и социальной помощи, кабинет здорового ребенка.<br style="box-sizing: border-box;"><br style="box-sizing: border-box;"></p>
            <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif; text-align: justify;'>Функционируют вспомогательные службы: клинико-диагностическая лаборатория, рентгенологическое отделение, кабинет ЭЭГ, УЗИ кабинеты, физиотерапия, ЛФК, массаж. Функционирует &laquo;Школа диабета&raquo;, &laquo;Артериальной гипертензии&raquo;, &laquo;Бронхиальной астмы&raquo;, &laquo;Ишемической болезни сердца&raquo;, &laquo;Школа подготовки к родам&raquo;.<br style="box-sizing: border-box;"><br style="box-sizing: border-box;"></p>
            <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif; text-align: justify;'>За годы проведения профилактических осмотров населения утвержденный план выполнялся на 100%, показатели выявления заболеваний среди осмотренных, взятия на диспансерный учет, а также оздоровление выявленных больных как среди взрослого населения, так и детей на уровне городских показателей.<br style="box-sizing: border-box;"><br style="box-sizing: border-box;"></p>
            <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif; text-align: justify;'>Поликлиника тесно сотрудничает с Национальным центром здорового образа жизни.<br style="box-sizing: border-box;"><br style="box-sizing: border-box;">С 2011 года поликлиника оказывает социально-психологическую помощь населению, в количестве 3 социальных работников и 3 психологов.<br style="box-sizing: border-box;"><br style="box-sizing: border-box;">С 2017 года в поликлинике работает отделение платных услуг, оказывающее весь спектр медицинских услуг. По итогам каждого месяца отделение приносит около миллиона тенге прибыли.</p>
        </section>
        <header class="article-header clearfix" style='box-sizing: border-box; display: block; clear: both; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
            <header class="article-header clearfix" style='box-sizing: border-box; display: block; clear: both; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
                <h1 class="article-title" style='box-sizing: border-box; font-size: 21.6px; margin: 0px; line-height: 1.15538em; font-family: "Open Sans"; font-weight: 300 !important; color: inherit; text-rendering: optimizelegibility; padding-top: 0.3em; padding-bottom: 0.1em; text-transform: uppercase; text-align: center;'><a href="http://gp8shymkent.kz/about/missiya-i-tsennosti/18-demo-content/138-missiya-i-tsennosti" style='box-sizing: border-box; background: transparent; color: inherit; text-decoration: none; transition: all 0.2s ease-in 0s; font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>МИССИЯ И ЦЕННОСТИ</a></h1>
            </header>
            <section class="article-content clearfix" style='box-sizing: border-box; display: block; clear: none; margin-top: 0px; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
                <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif; text-align: justify;'><strong style="box-sizing: border-box; font-weight: bold;">Миссия поликлиники</strong> &ndash; оказание качественной и эффективной медицинской помощи.<br style="box-sizing: border-box;">Наши опыт, знания и любовь к пациентам мы вкладываем в сохранение их здоровья и в здоровье будущих поколений.<br style="box-sizing: border-box;">ГКП на ПХВ &laquo;Шымкентская городская поликлиника № 8&raquo; стремится стать востребованной поликлиникой для населения, предоставляя только качественное лечение, повышая профессионализм и всегда думая с позиции пациента. Главным приоритетом поликлиника ставит уважение к жизни и направляет свою деятельность на благо пациентам.</p>
                <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif; text-align: justify;'><br style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bold;">Система ценностей</strong> поликлиники:<br style="box-sizing: border-box;">1. Здоровье пациента;<br style="box-sizing: border-box;">2. Индивидуальный подход каждому пациенту;<br style="box-sizing: border-box;">3. Соблюдение прав пациента;<br style="box-sizing: border-box;">4. Командная работа;<br style="box-sizing: border-box;">5. Социальная ответственность;<br style="box-sizing: border-box;">6. Профессиональный опыт и развитие;<br style="box-sizing: border-box;">7. &nbsp; &nbsp;Благоприятная атмосфера в коллективе.</p>
                <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif; text-align: justify;'>&nbsp;</p>
                <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif; text-align: justify;'><strong style="box-sizing: border-box; font-weight: bold;">Наши принципы</strong>:<br style="box-sizing: border-box;">1. Забота о пациенте &ndash; реализация прав пациентов на получение доступной, своевременной, безопасной и качественной медицинской помощи.<br style="box-sizing: border-box;">2. Законность &ndash; соблюдение нормативно-правовых актов, действующих в области охраны здоровья пациентов.<br style="box-sizing: border-box;">3. &nbsp; &nbsp;Непрерывное повышение профессионализма сотрудников поликлиники.</p>
            </section>
        </header>
        <section class="article-content clearfix" style='box-sizing: border-box; display: block; clear: none; margin-top: 0px; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'><br></section>
    <?php else: ?>
        <h1>
            <?= Yii::t('site', 'ГКП НА ПХВ "Городская поликлиника № 8"') ?>
        </h1>

        <p class="text-center">
            <img src="/img/fon.jpg" alt="building" style="width: 100%;">
        </p>

        <header class="article-header clearfix" style='box-sizing: border-box; display: block; clear: both; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
            <header class="article-header clearfix" style='box-sizing: border-box; display: block; clear: both; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
                <header class="article-header clearfix" style='box-sizing: border-box; display: block; clear: both; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
                    <h1 class="article-title" style='box-sizing: border-box; font-size: 21.6px; margin: 0px; line-height: 1.15538em; font-family: "Open Sans"; font-weight: 300 !important; color: inherit; text-rendering: optimizelegibility; padding-top: 0.3em; padding-bottom: 0.1em; text-transform: uppercase; text-align: center;'><a href="http://gp8shymkent.kz/kz/about/sfera-deyatelnosti/18-demo-content/157-yzmet-salasy" style='box-sizing: border-box; background: transparent; color: inherit; text-decoration: none; transition: all 0.2s ease-in 0s; font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>ҚЫЗМЕТ САЛАСЫ</a></h1>
                </header>
                <section class="article-content clearfix" style='box-sizing: border-box; display: block; clear: none; margin-top: 0px; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
                    <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>ОҚО Денсаулық сақтау басқармасының шаруашылық жүргізу құқығындағы &quot;№8 қалалық емхана&quot; мемлекеттік коммуналдық кәсіпорны Шымкент қаласының Еңбекшіқазақ және Әл-Фараби аудандарының 38000 астам тұрғындарының денсаулығын қорғау қызметін атқарып келеді. &nbsp;</p>
                    <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>&nbsp;</p>
                    <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>Емханада 18 сала мамандықтары бойынша дәрігерлер 2 отбасылық медицина бөлімшесінде, күндізгі стационарда, отбасын жоспарлау кабинетінде, профилактика және әлеуметтік көмек бөлімшесінде, дені сау балалар кабинетінде медициналық көмек көрсетеді.&nbsp;</p>
                    <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>Қосымша қызметтер: клиникалық-диагностикалық зертхана, рентгенология бөлімшесі, ЭЭГ, УДЗ кабинеттері, физиотерапия, ЕШК, массаж кабинеттері бар. &quot;Диабет мектебі&quot;, &quot;Артериялық гипертензия&quot;, &quot;Бронх демікпесі&quot;, &quot;Жүректің ишемиялық сырқаты&quot;, &quot;Босануға дайындау мектебі&quot; жұмыс істейді.&nbsp;</p>
                    <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>&nbsp;</p>
                    <p style='box-sizing: border-box; margin: 0px 0px 9px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; text-align: justify;'>Тұрғындарды профилактикалық тексеру жүргізу барысында қаралған науқастар арасында сырқаттарды анықтау, диспансерлік есепке алу көрсеткіштері, сонымен қатар ересектер тұрғындармен бірге балалар арасында анықталған ауруларды емдеу көрсеткіштері 100% орындалды.&nbsp;</p>
                    <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>Емхананың қызметі Ұлттық салауатты өмір салты орталығымен тығыз байланысты. 2011 жылдан бері емханада 3 әлеуметтік қызметкер және 3 психолог маман тұрғындарға әлеуметтік-психологиялық көмек көрсетіп келеді. Емханада 2017 жылдан бастап барлық медициналық қызмет түрлері қамтылған ақылы медициналық қызмет көрсету бөлімше жұмыс істейді. Әр айдың нәтижесі бойынша бөлімше бір миллион теңге көлемінде табыс келтіреді.&nbsp;</p>
                </section>
            </header>
            <section class="article-content clearfix" style='box-sizing: border-box; display: block; clear: none; margin-top: 0px; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'><br></section>
        </header>
        <section class="article-content clearfix" style='box-sizing: border-box; display: block; clear: none; margin-top: 0px; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'><br></section>
        <header class="article-header clearfix" style='box-sizing: border-box; display: block; clear: both; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
            <header class="article-header clearfix" style='box-sizing: border-box; display: block; clear: both; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
                <header class="article-header clearfix" style='box-sizing: border-box; display: block; clear: both; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
                    <header class="article-header clearfix" style='box-sizing: border-box; display: block; clear: both; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
                        <h1 class="article-title" style='box-sizing: border-box; font-size: 21.6px; margin: 0px; line-height: 1.15538em; font-family: "Open Sans"; font-weight: 300 !important; color: inherit; text-rendering: optimizelegibility; padding-top: 0.3em; padding-bottom: 0.1em; text-transform: uppercase; text-align: center;'><a href="http://gp8shymkent.kz/kz/about/missiya-i-tsennosti/18-demo-content/138-missiya-zh-ne-ndyly-tar" style='box-sizing: border-box; background: transparent; color: inherit; text-decoration: none; transition: all 0.2s ease-in 0s; font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>МИССИЯ ЖӘНЕ ҚҰНДЫЛЫҚТАР</a></h1>
                    </header>
                    <section class="article-content clearfix" style='box-sizing: border-box; display: block; clear: none; margin-top: 0px; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
                        <p style='box-sizing: border-box; margin: 0px 0px 9px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; text-align: justify;'><strong style="box-sizing: border-box; font-weight: bold;">Емхананың миссиясы&nbsp;</strong>&ndash; сапалы және тиімді медициналық көмек көрсету.&nbsp;</p>
                        <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>Тәжірибе мен білімді, науқасқа деген қайырымдылықты болашақ ұрпақтың және емделушілердің денсаулығын сақтауға жұмсаймыз. ШЖҚ №8 қалалық емхана&quot; МКК ұжымы кәсіпқойлығын арттыра отырып, емделуші мүддесін қорғау мен сапалы емдеу арқылы тұрғындардың жоғары сұранысына ие емхана болуға ұмтылады. Емхананың басты мақсаты - емделушілердің өмірін сақтау және бар қызметін олардың игілігіне бағыттау.&nbsp;</p>
                        <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>&nbsp;</p>
                        <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>Емхананың құндылықтар жүйесі:&nbsp;</p>
                        <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>1. Емделушінің денсаулығы;</p>
                        <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>2. Әрбір емделушіге жеке күтім;&nbsp;</p>
                        <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>3. Емделушілер құқығын қорғау;&nbsp;</p>
                        <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>4. Командалық жұмыс;&nbsp;</p>
                        <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>5. Әлеуметтік жауапкершілік;&nbsp;</p>
                        <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>6. Кәсіби тәжірибе және даму;&nbsp;</p>
                        <p style='box-sizing: border-box; margin: 0px 0px 9px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; text-align: justify;'>7. Ұжымдағы қолайлы ахуал.</p>
                        <p style='box-sizing: border-box; margin: 0px 0px 9px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; text-align: justify;'><strong style="box-sizing: border-box; font-weight: bold;">Қағидаттар</strong>:<br style="box-sizing: border-box;">1. &nbsp; &nbsp;Емделушіге қамқор болу - емделушілердің қолжетімді, қауіпсіз және сапалы медициналық көмекті иелену құқығын іске асыру. &nbsp;</p>
                        <p style='box-sizing: border-box; margin: 0px 0px 9px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; text-align: justify;'>2. &nbsp; &nbsp;Заңдылық &ndash; емделушілердің денсаулығын қорғау саласында қолданылатын нормативтік-құқықтық актілерді сақтау.&nbsp;</p>
                        <p style='box-sizing: border-box; margin: 0px 0px 5px; line-height: 1.3; color: rgb(51, 51, 51); font-weight: normal; font-family: "Open Sans", Helvetica, Arial, sans-serif;'>3. &nbsp;Емхана қызметкерлерінің кәсіпқойлығын үздіксіз арттыру.</p>
                    </section>
                </header>
            </header>
        </header>
        <section class="article-content clearfix" style='box-sizing: border-box; display: block; clear: none; margin-top: 0px; color: rgb(51, 51, 51); font-family: "Open Sans", Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'><br></section>
    <?php endif; ?>
</div>
